### ISSUE TITLE
Error in facebook.ejs 

### ISSUE THREAD

**Issue by mstumpf585** [MaSUB/GoodBoysInc#15]
So I got it to work for once where it returned 860 words in the json file and sent that to watson. However, I tried testing it a 2nd time and now I get this strange error. Was wondering if anyone knew what this was? 

facebook:108 connected
facebook:142 58
facebook:169 128
facebook:169 151
facebook:169 161
facebook:169 287
facebook:169 409
facebook:169 504
facebook:169 524
sdk.js:95 Uncaught TypeError: Cannot read property 'next' of undefined
    at facebook:168
    at v.__wrapper (sdk.js:95)
    at ma (sdk.js:105)
    at Object.w (sdk.js:103)
    at Object.<anonymous> (sdk.js:41)
    at posts?access_token=EAAZAQKQ42ZBMUBACPfyCXRWfol38kWSEBYZA41rKaoqel3oRgTdRnNsWdhh0aL5zrjeeVSq8XYOFfOw…:1
(anonymous) @ facebook:168
v.__wrapper @ sdk.js:95
ma @ sdk.js:105
w @ sdk.js:103
(anonymous) @ sdk.js:41
(anonymous) @ posts?access_token=EAAZAQKQ42ZBMUBACPfyCXRWfol38kWSEBYZA41rKaoqel3oRgTdRnNsWdhh0aL5zrjeeVSq8XYOFfOw…:1

**Comment by mstumpf585** [comment]
Seems like this goes away after some amount of time.  Also got this message from FB "Service Worker termination by a timeout timer was canceled because DevTools is attached."

**Comment by mstumpf585** [comment]
Turns out my facebook post just didn't have enough words so the system called the API to many times. I add an if that handles this problem in the ejs

**Comment by MaSUB** [comment]
You are the best mike 🥇
